### PR TITLE
Pull request to add game instructions and screenshot

### PR DESCRIPTION
**Pull request by kimothokamau**
For this section of the project, we took on writing an elaborate set of instructions to properly instruct potential users of any skill and knowledge level how to play the game on the live tester that is deployed on the README file. The instructions are placed on the "how to play the game" section.

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes
**Hi team!**
**Great job so far on this milestone :clap::clap:. However, there are still a few changes we need to make to get this project approved :muscle:.**

- [x] Kindly improved the project pull request to look more professional. see screenshots [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for guidance

- [x] No game-logic should be present in the main.rb ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright])

 [Optional] Ideally, there should be a Player class and @players attribute in Game class which is an array that stores the Player instances.

Make the required changes and request for another review when you are done.
You can reach me on slack @ Eric Enaburekhan if you have any questions.

Happy Coding:blush:
Eric Enaburekhan

**Comment by franklinben23** [comment]
- edited the pull request title and comment to be more precise and a lot more descriptive. oozes professionalism overall.
- There is no game logic on the main, I think you are mistaken, there are only functions controlling game flow on the main (see they check and control all of the methods that are actually processing the game, those are in different classes), they must be there because that's where the puts are, what the players will see.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: 
---------
Hello team!! :wave: Excellent job so far :clap: ç
However, there are a few changes to work on.
------------

- [x] Explain better step by step 'GETTING STARTED', Remember to write the step by step as if the person that is trying to use this repository doesn't know anything about programming.
For me, if I follow step by step the game throws me an error, you write to run 'ruby main.rb' you forgot to mention that you have to be inside the directory 'bin' or run the command 'ruby bin/main.rb
- [x] Write the rules of the game, how you win that you can or cannot do, etc.
Screenshot from 2021-01-25 19-15-14

- [x] [OPTIONAL] Check if the live demo it's working properly, for me doesn't run.

-------------
Make these changes and send it again for review. :muscle: 
HAPPY CODING!! 
MB5W4D

**Review by cristianCeamatu — APPROVED** [review]
### 🥇 APPROVED 🥇 Congratulations and good luck with the next projects!

If you ever need any help or notice that you are wasting too many hours on a bug don't hesitate to contact me on Slack.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Pull request merged**
